### PR TITLE
fix: use `toml_edit` to construct inline tables with correct escaping

### LINKED ISSUE #87: Escape paths when adding them to toml
# Problem

This code can panic

https://github.com/eopb/cargo-override/blob/79e6cb25779c085bdb70f53028d6bfd28dc07363/src/toml.rs#L71

### PR DESCRIPTION
**Pull request by eopb**
fixes #87

### CODE REVIEW

File: src/toml.rs [hunk 1]
```diff
@@ -53,25 +61,29 @@ fn source(working_dir: &Path, manifest_directory: &Path, mode: &context::Mode) -
                 relative_path.into()
             };
 
-            format!("{{ path = \"{}\" }}", path.display())
+            let path = path
+                .as_os_str()
+                .to_str()
+                .expect("path must be utf8 unicode");
```
Comment (eopb) [inline src/toml.rs:67]: It's not great panicking here, but it's still better than what we had before
